### ISSUE TITLE
Wizard Wars

### ISSUE THREAD

**Issue by GregHib** [dusk-rs/dusk#132]
The tree's west of Edgeville monastery reminded me of a game I used to play [Magicka: Wizard Wars](https://www.youtube.com/watch?v=NS-Hj4MCKvw) and it got me thinking, that style of gameplay would fit perfectly as a mini-game and there's already the [Great Orb Project](https://runescape.fandom.com/wiki/The_Great_Orb_Project) items & spells with which to do so.

**Comment by Tyluur** [comment]
I never played the game, and google wasn't of much help [https://i.imgur.com/RGHDsU0.png]. I'm not sure what this is suggesting!

**Comment by GregHib** [comment]
> google wasn't of much help

It was a magic arena game see https://www.youtube.com/watch?v=NWLENZk-TyM

Essentially envision this; a custom map, maybe only a region or two in size. Where two teams are pitched against each other in PVP. However, it's magic only and projectiles can be blocked by barriers.

Magic only soul-wars or fist-of-guthix if you will.

**Comment by Tyluur** [comment]
Love it

**Comment by Tyluur** [comment]
Perhaps it can be a way to introduce lunars or ancient magicks? Or spell packs (https://oldschoolrunescape.fandom.com/wiki/Item_pack), since it's entirely based on magic. We can also blend the great orb project's orb collection as well as wizard wars into 1 minigame with two phases. The first being for rune collection (orbs) and the second being for fighting using the runes each team collected.

**Comment by GregHib** [comment]
Yep lots of options for rewards; enchanting (i), wands, spell unlocks, infinity, runecrafting gear, combo runes, dungeoneering magic rewards etc...

Rewards needs to be looked at a global level on what minigames/bosses should give what reward to give balance
